#ifndef STATE_DEFINES_H_
#define STATE_DEFINES_H_

#include "freertos/FreeRTOS.h"
#include "freertos/event_groups.h"
#include <cstdint>

namespace Node_Core
{

enum class State
{
	DEVICE_ON,
	DEVICE_OK,
	DEVICE_SETUP,
	DEVICE_READY,
	READY_TO_PROCEED,
	TEST_START,
	TEST_RUNNING,
	CURRENT_TEST_CHECK,
	CURRENT_TEST_OK, // Added CURRENT_TEST_OK
	READY_NEXT_TEST,
	MANUAL_NEXT_TEST,
	RETEST,
	SYSTEM_PAUSED,
	ALL_TEST_DONE,
	START_FROM_SAVE,
	RECOVER_DATA,
	ADDENDUM_TEST_DATA,
	FAILED_TEST,
	TRANSPORT_DATA,
	SYSTEM_TUNING,
	FAULT,
	USER_CHECK_REQUIRED,
	WAITING_FOR_USER,
	MAX_STATE
};

enum class Event : u_int32_t
{ // System Events
	NONE,
	ERROR,
	SYSTEM_FAULT,
	FAULT_CLEARED,
	NETWORK_DISCONNECTED,
	RESTART,
	// System init events
	SETTING_LOADED,
	SELF_CHECK_OK,
	LOAD_BANK_CHECKED,
	// TestEvents
	TEST_RUN_OK,
	TEST_TIME_END,
	DATA_CAPTURED,
	VALID_DATA,
	TEST_FAILED,
	RETEST,
	TEST_LIST_EMPTY,
	PENDING_TEST_FOUND,
	REJECT_CURRENT_TEST,
	// User commands
	START,
	STOP,
	AUTO,
	MANUAL,
	PAUSE,
	RESUME,
	// User Updates
	USER_TUNE,
	DATA_ENTRY,
	NEW_TEST,
	DELETE_TEST,
	// Data Events
	SAVE,
	JSON_READY
};



} // namespace Node_Core

#endif // STATE_DEFINES_H_
